Repository HSU-Web-Framework1-Artory/Artory, pull requests merged in 2024-12, with the labels that each got.

#81 🚨 Mypage 페이지 - 데이터 처리 로직 수정
  src/entites/Home/Footer.jsx
  src/entites/MyPage/Carousel.jsx
  src/entites/MyPage/InfoSection.jsx
  src/entites/MyPage/ProfileSection.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/shared/components/StandardPoster.jsx
  src/shared/dummy/StoryDummy.jsx
  src/shared/dummy/UserDummy.jsx
Labels: 🎨 Fix, :umbrella: khyaejin, :recycle: Refactoring

#88 :sparkles: 추천 로직 추가
  src/entites/Story/Carousel.jsx
  src/pages/ExhibitionList.jsx
  src/pages/Onboarding3.jsx
  src/shared/dummy/ExhibitionDummy.jsx
Labels: :sparkles: Feat, :rabbit: frombunny

#90 ♻️ 최종 제출 전 코드 리팩토링 - 폴더 구조 및 디테일 수정
  src/css/posterSection.css
  src/entites/Home/PosterSection.jsx
  src/pages/Exhibition.jsx
  src/pages/ExhibitionDetail.jsx
  src/pages/ExhibitionList.jsx
  src/pages/ExhibitionSearch.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/pages/MyStory.jsx
  src/pages/Story.jsx
  src/shared/components/Footer.jsx
Labels: :umbrella: khyaejin, :recycle: Refactoring

#91 ♻️ StandardPoster - isSaveClicked 로직 리팩터링
  src/entites/Story/Carousel.jsx
  src/shared/components/StandardPoster.jsx
Labels: :umbrella: khyaejin, :recycle: Refactoring
